api:
  base_url: localhost:8080
sensors:
  - name: High Dynamic Range Digital Light
    model: TSL2591
    module: adafruit_tsl2591
    constructor: TSL2591
    type: i2c
    measurements:
    - check_every: 10
      name: Lux
      symbol: lx
      function: lux
      threshold: 0.05
  - name: Barometric Pressure/Altitude/Temperature Sensor
    model: MPL3115A2
    module: adafruit_mpl3115a2
    constructor: MPL3115A2
    type: i2c
    measurements:
    - check_every: 10
      name: Celsius
      symbol: C
      function: temperature
      threshold: 0.05
    - check_every: 0
      name: Pascal
      symbol: Pa
      function: pressure
      threshold: 0.05
  - name: Microphone
    type: mic
    min_clip_size: 5
    max_clip_size: 15
    max_time_between_noises: 5
rq_worker:
        queues:
                - post