version: "2"
services:
  db:
    image: "redis"
    container_name: "redis"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  sensors:
    depends_on:
      - db
    container_name: "Raspy Sensor"
    restart: always
    build:
      context: ./sensor
    volumes:
      - /proc/cpuinfo:/proc/cpuinfo

  worker:
    depends_on:
      - sensors
      - db
    container_name: "Job Worker"
    restart: always
    build:
      context: ./sensor
      dockerfile: WorkerDockerfile
      args:
        jobqueue: "post"
#  flask:
#    restart: always
#    build:
#      context: ./dashboard
#    expose:
#      - "8000"
volumes:
  my_dbdata:
