FROM balenalib/rpi-raspbian:latest
ENTRYPOINT []

RUN apt-get -q update && \
	apt-get -qy install \
        python3 python3-pip \
        python-dev python-pip gcc make  

RUN pip3 install -r requirements.txt

