#!/bin/bash

FROM balenalib/rpi-raspbian:latest
ENTRYPOINT []


RUN apt-get update -y
RUN apt-get install -y python3 python-pip-whl python3-pip python3-setuptools curl python3.5-dev
RUN rm -rf /var/lib/apt/lists/*


COPY . /app
WORKDIR /app
RUN pip3 install wheel
RUN pip3 install -r /app/requirements.txt

ARG jobqueue
CMD ["python3","-u", "/app/rq_worker.py", "$jobqueue"]